### ISSUE TITLE
User friendly customized domain setup

### ISSUE THREAD

**Issue by h4x3rotab** [Phala-Network/phala-cloud#21]
We already have:

- [Customized domain support in dstack-gateway](https://github.com/Dstack-TEE/dstack?tab=readme-ov-file#reverse-proxy-tls-passthrough)
- [Script to set up TLS certificate for customized domain](https://github.com/Dstack-TEE/dstack?tab=readme-ov-file#reverse-proxy-tls-passthrough)

But it's not user friendly enough. We need:

- A simple guide on how to set up cloudflare, or even a script that can set it up automatically from the CVM
- A simple docker image to cover the cert setup and reverse proxy. So users can easily include the container and config a few env vars.

Ideally it should be like:

```
services:
  cloud-ingress:
    image: @phala/cloud-ingress:v1
    environment:
      - DOMAIN=$DOMAIN
      - TPROXY_DOMAIN=$TPROXY_DOMAIN
      - CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN
      - CLOUDFLARE_ZONE_ID=$CLOUDFLARE_ZONE_ID
      - CERTBOT_EMAIL=$CERTBOT_EMAIL
      - TARGET_ENDPOINT=http://app:80
  app:
     image: your-app
     ports:
       - 80:80
```
